### ISSUE TITLE
(priority) Redirect users by clicking on a contributor's image

### ISSUE THREAD

**Issue by RaulCatalinas** [polacodev/dev-libraries#8]
I think we could redirect users to a social network (e.g. GitHub) when users click on the image of one of the contributors.

**Comment by polacodev** [comment]
> Creo que podríamos redirigir a los usuarios a una red social (por ejemplo GitHub) cuando los usuarios dan clic en la imagen de uno de los contribuidores

sounds great, I like it

**Comment by polacodev** [comment]
added a new property to the contributors content type **contributorGithubURL**
